namespace Blowfish
{
	partial class Form1
	{
		/// <summary>
		/// Обязательная переменная конструктора.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// Освободить все используемые ресурсы.
		/// </summary>
		/// <param name="disposing">истинно, если управляемый ресурс должен быть удален; иначе ложно.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}

		#region Код, автоматически созданный конструктором форм Windows

		/// <summary>
		/// Требуемый метод для поддержки конструктора — не изменяйте 
		/// содержимое этого метода с помощью редактора кода.
		/// </summary>
		private void InitializeComponent()
		{
			System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges12 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			this.panel1 = new System.Windows.Forms.Panel();
			this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
			this.label1 = new System.Windows.Forms.Label();
			this.bunifuButton3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			this.bunifuButton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			this.panel2 = new System.Windows.Forms.Panel();
			this.bunifuButton5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			this.bunifuButton4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			this.panel3 = new System.Windows.Forms.Panel();
			this.bunifuTextBox1 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
			this.bunifuTextBox2 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
			this.label2 = new System.Windows.Forms.Label();
			this.bunifuTextBox3 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
			this.bunifuTextBox4 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
			this.bunifuTextBox5 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
			this.bunifuTextBox6 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
			this.label3 = new System.Windows.Forms.Label();
			this.label4 = new System.Windows.Forms.Label();
			this.label5 = new System.Windows.Forms.Label();
			this.label6 = new System.Windows.Forms.Label();
			this.bunifuButton6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			this.bunifuFormDock1 = new Bunifu.UI.WinForms.BunifuFormDock();
			this.panel1.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
			this.panel2.SuspendLayout();
			this.SuspendLayout();
			// 
			// panel1
			// 
			this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(75)))), ((int)(((byte)(105)))));
			this.panel1.Controls.Add(this.bunifuPictureBox1);
			this.panel1.Controls.Add(this.label1);
			this.panel1.Controls.Add(this.bunifuButton3);
			this.panel1.Controls.Add(this.bunifuButton2);
			this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
			this.panel1.ImeMode = System.Windows.Forms.ImeMode.On;
			this.panel1.Location = new System.Drawing.Point(0, 0);
			this.panel1.Name = "panel1";
			this.panel1.Size = new System.Drawing.Size(872, 42);
			this.panel1.TabIndex = 0;
			this.panel1.MouseDown += new System.Windows.Forms.MouseEventHandler(this.panel1_MouseDown);
			// 
			// bunifuPictureBox1
			// 
			this.bunifuPictureBox1.AllowFocused = false;
			this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
			this.bunifuPictureBox1.BorderRadius = 0;
			this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
			this.bunifuPictureBox1.IsCircle = false;
			this.bunifuPictureBox1.Location = new System.Drawing.Point(17, 5);
			this.bunifuPictureBox1.Name = "bunifuPictureBox1";
			this.bunifuPictureBox1.Size = new System.Drawing.Size(32, 32);
			this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.bunifuPictureBox1.TabIndex = 3;
			this.bunifuPictureBox1.TabStop = false;
			this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Custom;
			// 
			// label1
			// 
			this.label1.AutoSize = true;
			this.label1.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
			this.label1.ForeColor = System.Drawing.Color.White;
			this.label1.Location = new System.Drawing.Point(60, 10);
			this.label1.Name = "label1";
			this.label1.Size = new System.Drawing.Size(480, 23);
			this.label1.TabIndex = 4;
			this.label1.Text = "Электронная цифровая подпись (алгоритм DSA)";
			this.label1.AutoSizeChanged += new System.EventHandler(this.Form1_Load);
			// 
			// bunifuButton3
			// 
			this.bunifuButton3.AllowToggling = false;
			this.bunifuButton3.AnimationSpeed = 200;
			this.bunifuButton3.AutoGenerateColors = false;
			this.bunifuButton3.BackColor = System.Drawing.Color.Transparent;
			this.bunifuButton3.BackColor1 = System.Drawing.Color.Transparent;
			this.bunifuButton3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton3.BackgroundImage")));
			this.bunifuButton3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton3.ButtonText = "_";
			this.bunifuButton3.ButtonTextMarginLeft = 0;
			this.bunifuButton3.ColorContrastOnClick = 45;
			this.bunifuButton3.ColorContrastOnHover = 45;
			this.bunifuButton3.Cursor = System.Windows.Forms.Cursors.Hand;
			borderEdges7.BottomLeft = true;
			borderEdges7.BottomRight = true;
			borderEdges7.TopLeft = true;
			borderEdges7.TopRight = true;
			this.bunifuButton3.CustomizableEdges = borderEdges7;
			this.bunifuButton3.DialogResult = System.Windows.Forms.DialogResult.None;
			this.bunifuButton3.DisabledBorderColor = System.Drawing.Color.Empty;
			this.bunifuButton3.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuButton3.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.bunifuButton3.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			this.bunifuButton3.Font = new System.Drawing.Font("Arial Unicode MS", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
			this.bunifuButton3.ForeColor = System.Drawing.Color.White;
			this.bunifuButton3.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
			this.bunifuButton3.IconMarginLeft = 11;
			this.bunifuButton3.IconPadding = 10;
			this.bunifuButton3.IconRightCursor = System.Windows.Forms.Cursors.Hand;
			this.bunifuButton3.IdleBorderColor = System.Drawing.Color.Transparent;
			this.bunifuButton3.IdleBorderRadius = 2;
			this.bunifuButton3.IdleBorderThickness = 2;
			this.bunifuButton3.IdleFillColor = System.Drawing.Color.Transparent;
			this.bunifuButton3.IdleIconLeftImage = null;
			this.bunifuButton3.IdleIconRightImage = null;
			this.bunifuButton3.IndicateFocus = false;
			this.bunifuButton3.Location = new System.Drawing.Point(816, 9);
			this.bunifuButton3.Name = "bunifuButton3";
			this.bunifuButton3.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.bunifuButton3.onHoverState.BorderRadius = 2;
			this.bunifuButton3.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton3.onHoverState.BorderThickness = 2;
			this.bunifuButton3.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.bunifuButton3.onHoverState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton3.onHoverState.IconLeftImage = null;
			this.bunifuButton3.onHoverState.IconRightImage = null;
			this.bunifuButton3.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
			this.bunifuButton3.OnIdleState.BorderRadius = 2;
			this.bunifuButton3.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton3.OnIdleState.BorderThickness = 2;
			this.bunifuButton3.OnIdleState.FillColor = System.Drawing.Color.Transparent;
			this.bunifuButton3.OnIdleState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton3.OnIdleState.IconLeftImage = null;
			this.bunifuButton3.OnIdleState.IconRightImage = null;
			this.bunifuButton3.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
			this.bunifuButton3.OnPressedState.BorderRadius = 2;
			this.bunifuButton3.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton3.OnPressedState.BorderThickness = 2;
			this.bunifuButton3.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
			this.bunifuButton3.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton3.OnPressedState.IconLeftImage = null;
			this.bunifuButton3.OnPressedState.IconRightImage = null;
			this.bunifuButton3.Size = new System.Drawing.Size(16, 18);
			this.bunifuButton3.TabIndex = 3;
			this.bunifuButton3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.bunifuButton3.TextMarginLeft = 0;
			this.bunifuButton3.UseDefaultRadiusAndThickness = true;
			this.bunifuButton3.AutoSizeChanged += new System.EventHandler(this.Form1_Load);
			this.bunifuButton3.Click += new System.EventHandler(this.bunifuButton3_Click);
			// 
			// bunifuButton2
			// 
			this.bunifuButton2.AllowToggling = false;
			this.bunifuButton2.AnimationSpeed = 200;
			this.bunifuButton2.AutoGenerateColors = true;
			this.bunifuButton2.AutoSize = true;
			this.bunifuButton2.BackColor = System.Drawing.Color.Transparent;
			this.bunifuButton2.BackColor1 = System.Drawing.Color.Transparent;
			this.bunifuButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.BackgroundImage")));
			this.bunifuButton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton2.ButtonText = "X";
			this.bunifuButton2.ButtonTextMarginLeft = 0;
			this.bunifuButton2.ColorContrastOnClick = 45;
			this.bunifuButton2.ColorContrastOnHover = 45;
			this.bunifuButton2.Cursor = System.Windows.Forms.Cursors.Hand;
			borderEdges8.BottomLeft = true;
			borderEdges8.BottomRight = true;
			borderEdges8.TopLeft = true;
			borderEdges8.TopRight = true;
			this.bunifuButton2.CustomizableEdges = borderEdges8;
			this.bunifuButton2.DialogResult = System.Windows.Forms.DialogResult.None;
			this.bunifuButton2.DisabledBorderColor = System.Drawing.Color.Empty;
			this.bunifuButton2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuButton2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.bunifuButton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			this.bunifuButton2.Font = new System.Drawing.Font("Arial Unicode MS", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
			this.bunifuButton2.ForeColor = System.Drawing.Color.White;
			this.bunifuButton2.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
			this.bunifuButton2.IconMarginLeft = 11;
			this.bunifuButton2.IconPadding = 10;
			this.bunifuButton2.IconRightCursor = System.Windows.Forms.Cursors.Hand;
			this.bunifuButton2.IdleBorderColor = System.Drawing.Color.Transparent;
			this.bunifuButton2.IdleBorderRadius = 3;
			this.bunifuButton2.IdleBorderThickness = 1;
			this.bunifuButton2.IdleFillColor = System.Drawing.Color.Transparent;
			this.bunifuButton2.IdleIconLeftImage = null;
			this.bunifuButton2.IdleIconRightImage = null;
			this.bunifuButton2.IndicateFocus = false;
			this.bunifuButton2.Location = new System.Drawing.Point(840, 12);
			this.bunifuButton2.Name = "bunifuButton2";
			this.bunifuButton2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			this.bunifuButton2.onHoverState.BorderRadius = 3;
			this.bunifuButton2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton2.onHoverState.BorderThickness = 1;
			this.bunifuButton2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
			this.bunifuButton2.onHoverState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton2.onHoverState.IconLeftImage = null;
			this.bunifuButton2.onHoverState.IconRightImage = null;
			this.bunifuButton2.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
			this.bunifuButton2.OnIdleState.BorderRadius = 3;
			this.bunifuButton2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton2.OnIdleState.BorderThickness = 1;
			this.bunifuButton2.OnIdleState.FillColor = System.Drawing.Color.Transparent;
			this.bunifuButton2.OnIdleState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton2.OnIdleState.IconLeftImage = null;
			this.bunifuButton2.OnIdleState.IconRightImage = null;
			this.bunifuButton2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))));
			this.bunifuButton2.OnPressedState.BorderRadius = 3;
			this.bunifuButton2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton2.OnPressedState.BorderThickness = 1;
			this.bunifuButton2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))), ((int)(((byte)(140)))));
			this.bunifuButton2.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton2.OnPressedState.IconLeftImage = null;
			this.bunifuButton2.OnPressedState.IconRightImage = null;
			this.bunifuButton2.Size = new System.Drawing.Size(18, 18);
			this.bunifuButton2.TabIndex = 2;
			this.bunifuButton2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.bunifuButton2.TextMarginLeft = 0;
			this.bunifuButton2.UseDefaultRadiusAndThickness = true;
			this.bunifuButton2.AutoSizeChanged += new System.EventHandler(this.Form1_Load);
			this.bunifuButton2.Click += new System.EventHandler(this.bunifuButton2_Click);
			// 
			// bunifuButton1
			// 
			this.bunifuButton1.AllowToggling = false;
			this.bunifuButton1.AnimationSpeed = 200;
			this.bunifuButton1.AutoGenerateColors = false;
			this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
			this.bunifuButton1.BackColor1 = System.Drawing.Color.Transparent;
			this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
			this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
			this.bunifuButton1.ButtonText = "Подписать";
			this.bunifuButton1.ButtonTextMarginLeft = 0;
			this.bunifuButton1.ColorContrastOnClick = 45;
			this.bunifuButton1.ColorContrastOnHover = 45;
			this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Hand;
			borderEdges9.BottomLeft = true;
			borderEdges9.BottomRight = true;
			borderEdges9.TopLeft = true;
			borderEdges9.TopRight = true;
			this.bunifuButton1.CustomizableEdges = borderEdges9;
			this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
			this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.Empty;
			this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			this.bunifuButton1.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
			this.bunifuButton1.ForeColor = System.Drawing.Color.White;
			this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
			this.bunifuButton1.IconMarginLeft = 7;
			this.bunifuButton1.IconPadding = 4;
			this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Hand;
			this.bunifuButton1.IdleBorderColor = System.Drawing.Color.White;
			this.bunifuButton1.IdleBorderRadius = 3;
			this.bunifuButton1.IdleBorderThickness = 1;
			this.bunifuButton1.IdleFillColor = System.Drawing.Color.Transparent;
			this.bunifuButton1.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.IdleIconLeftImage")));
			this.bunifuButton1.IdleIconRightImage = null;
			this.bunifuButton1.IndicateFocus = false;
			this.bunifuButton1.Location = new System.Drawing.Point(9, 74);
			this.bunifuButton1.Name = "bunifuButton1";
			this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.bunifuButton1.onHoverState.BorderRadius = 3;
			this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton1.onHoverState.BorderThickness = 1;
			this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton1.onHoverState.IconLeftImage = null;
			this.bunifuButton1.onHoverState.IconRightImage = null;
			this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.White;
			this.bunifuButton1.OnIdleState.BorderRadius = 3;
			this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
			this.bunifuButton1.OnIdleState.BorderThickness = 1;
			this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.Transparent;
			this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton1.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.OnIdleState.IconLeftImage")));
			this.bunifuButton1.OnIdleState.IconRightImage = null;
			this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
			this.bunifuButton1.OnPressedState.BorderRadius = 3;
			this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton1.OnPressedState.BorderThickness = 1;
			this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
			this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton1.OnPressedState.IconLeftImage = null;
			this.bunifuButton1.OnPressedState.IconRightImage = null;
			this.bunifuButton1.Size = new System.Drawing.Size(172, 32);
			this.bunifuButton1.TabIndex = 1;
			this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.bunifuButton1.TextMarginLeft = 0;
			this.bunifuButton1.UseDefaultRadiusAndThickness = true;
			this.bunifuButton1.AutoSizeChanged += new System.EventHandler(this.Form1_Load);
			this.bunifuButton1.Click += new System.EventHandler(this.bunifuButton1_Click);
			// 
			// panel2
			// 
			this.panel2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(49)))), ((int)(((byte)(69)))));
			this.panel2.Controls.Add(this.bunifuButton5);
			this.panel2.Controls.Add(this.bunifuButton4);
			this.panel2.Controls.Add(this.bunifuButton1);
			this.panel2.Controls.Add(this.panel3);
			this.panel2.Dock = System.Windows.Forms.DockStyle.Left;
			this.panel2.Location = new System.Drawing.Point(0, 42);
			this.panel2.Name = "panel2";
			this.panel2.Size = new System.Drawing.Size(184, 468);
			this.panel2.TabIndex = 2;
			this.panel2.AutoSizeChanged += new System.EventHandler(this.Form1_Load);
			// 
			// bunifuButton5
			// 
			this.bunifuButton5.AllowToggling = false;
			this.bunifuButton5.AnimationSpeed = 200;
			this.bunifuButton5.AutoGenerateColors = false;
			this.bunifuButton5.BackColor = System.Drawing.Color.Transparent;
			this.bunifuButton5.BackColor1 = System.Drawing.Color.Transparent;
			this.bunifuButton5.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton5.BackgroundImage")));
			this.bunifuButton5.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
			this.bunifuButton5.ButtonText = "Обзор";
			this.bunifuButton5.ButtonTextMarginLeft = 0;
			this.bunifuButton5.ColorContrastOnClick = 45;
			this.bunifuButton5.ColorContrastOnHover = 45;
			this.bunifuButton5.Cursor = System.Windows.Forms.Cursors.Hand;
			borderEdges10.BottomLeft = true;
			borderEdges10.BottomRight = true;
			borderEdges10.TopLeft = true;
			borderEdges10.TopRight = true;
			this.bunifuButton5.CustomizableEdges = borderEdges10;
			this.bunifuButton5.DialogResult = System.Windows.Forms.DialogResult.None;
			this.bunifuButton5.DisabledBorderColor = System.Drawing.Color.Empty;
			this.bunifuButton5.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuButton5.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.bunifuButton5.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			this.bunifuButton5.Font = new System.Drawing.Font("Century Gothic", 12F);
			this.bunifuButton5.ForeColor = System.Drawing.Color.White;
			this.bunifuButton5.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
			this.bunifuButton5.IconMarginLeft = 7;
			this.bunifuButton5.IconPadding = 4;
			this.bunifuButton5.IconRightCursor = System.Windows.Forms.Cursors.Hand;
			this.bunifuButton5.IdleBorderColor = System.Drawing.Color.White;
			this.bunifuButton5.IdleBorderRadius = 3;
			this.bunifuButton5.IdleBorderThickness = 1;
			this.bunifuButton5.IdleFillColor = System.Drawing.Color.Transparent;
			this.bunifuButton5.IdleIconLeftImage = null;
			this.bunifuButton5.IdleIconRightImage = null;
			this.bunifuButton5.IndicateFocus = false;
			this.bunifuButton5.Location = new System.Drawing.Point(9, 150);
			this.bunifuButton5.Name = "bunifuButton5";
			this.bunifuButton5.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.bunifuButton5.onHoverState.BorderRadius = 3;
			this.bunifuButton5.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton5.onHoverState.BorderThickness = 1;
			this.bunifuButton5.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.bunifuButton5.onHoverState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton5.onHoverState.IconLeftImage = null;
			this.bunifuButton5.onHoverState.IconRightImage = null;
			this.bunifuButton5.OnIdleState.BorderColor = System.Drawing.Color.White;
			this.bunifuButton5.OnIdleState.BorderRadius = 3;
			this.bunifuButton5.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
			this.bunifuButton5.OnIdleState.BorderThickness = 1;
			this.bunifuButton5.OnIdleState.FillColor = System.Drawing.Color.Transparent;
			this.bunifuButton5.OnIdleState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton5.OnIdleState.IconLeftImage = null;
			this.bunifuButton5.OnIdleState.IconRightImage = null;
			this.bunifuButton5.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
			this.bunifuButton5.OnPressedState.BorderRadius = 3;
			this.bunifuButton5.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton5.OnPressedState.BorderThickness = 1;
			this.bunifuButton5.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
			this.bunifuButton5.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton5.OnPressedState.IconLeftImage = null;
			this.bunifuButton5.OnPressedState.IconRightImage = null;
			this.bunifuButton5.Size = new System.Drawing.Size(172, 29);
			this.bunifuButton5.TabIndex = 5;
			this.bunifuButton5.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.bunifuButton5.TextMarginLeft = 0;
			this.bunifuButton5.UseDefaultRadiusAndThickness = true;
			this.bunifuButton5.AutoSizeChanged += new System.EventHandler(this.Form1_Load);
			this.bunifuButton5.Click += new System.EventHandler(this.bunifuButton5_Click);
			// 
			// bunifuButton4
			// 
			this.bunifuButton4.AllowToggling = false;
			this.bunifuButton4.AnimationSpeed = 200;
			this.bunifuButton4.AutoGenerateColors = false;
			this.bunifuButton4.BackColor = System.Drawing.Color.Transparent;
			this.bunifuButton4.BackColor1 = System.Drawing.Color.Transparent;
			this.bunifuButton4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton4.BackgroundImage")));
			this.bunifuButton4.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
			this.bunifuButton4.ButtonText = "Проверить";
			this.bunifuButton4.ButtonTextMarginLeft = 0;
			this.bunifuButton4.ColorContrastOnClick = 45;
			this.bunifuButton4.ColorContrastOnHover = 45;
			this.bunifuButton4.Cursor = System.Windows.Forms.Cursors.Hand;
			borderEdges11.BottomLeft = true;
			borderEdges11.BottomRight = true;
			borderEdges11.TopLeft = true;
			borderEdges11.TopRight = true;
			this.bunifuButton4.CustomizableEdges = borderEdges11;
			this.bunifuButton4.DialogResult = System.Windows.Forms.DialogResult.None;
			this.bunifuButton4.DisabledBorderColor = System.Drawing.Color.Empty;
			this.bunifuButton4.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuButton4.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.bunifuButton4.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			this.bunifuButton4.Font = new System.Drawing.Font("Century Gothic", 12F);
			this.bunifuButton4.ForeColor = System.Drawing.Color.White;
			this.bunifuButton4.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
			this.bunifuButton4.IconMarginLeft = 7;
			this.bunifuButton4.IconPadding = 4;
			this.bunifuButton4.IconRightCursor = System.Windows.Forms.Cursors.Hand;
			this.bunifuButton4.IdleBorderColor = System.Drawing.Color.White;
			this.bunifuButton4.IdleBorderRadius = 3;
			this.bunifuButton4.IdleBorderThickness = 1;
			this.bunifuButton4.IdleFillColor = System.Drawing.Color.Transparent;
			this.bunifuButton4.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton4.IdleIconLeftImage")));
			this.bunifuButton4.IdleIconRightImage = null;
			this.bunifuButton4.IndicateFocus = false;
			this.bunifuButton4.Location = new System.Drawing.Point(9, 112);
			this.bunifuButton4.Name = "bunifuButton4";
			this.bunifuButton4.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.bunifuButton4.onHoverState.BorderRadius = 3;
			this.bunifuButton4.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton4.onHoverState.BorderThickness = 1;
			this.bunifuButton4.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.bunifuButton4.onHoverState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton4.onHoverState.IconLeftImage = null;
			this.bunifuButton4.onHoverState.IconRightImage = null;
			this.bunifuButton4.OnIdleState.BorderColor = System.Drawing.Color.White;
			this.bunifuButton4.OnIdleState.BorderRadius = 3;
			this.bunifuButton4.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
			this.bunifuButton4.OnIdleState.BorderThickness = 1;
			this.bunifuButton4.OnIdleState.FillColor = System.Drawing.Color.Transparent;
			this.bunifuButton4.OnIdleState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton4.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton4.OnIdleState.IconLeftImage")));
			this.bunifuButton4.OnIdleState.IconRightImage = null;
			this.bunifuButton4.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
			this.bunifuButton4.OnPressedState.BorderRadius = 3;
			this.bunifuButton4.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton4.OnPressedState.BorderThickness = 1;
			this.bunifuButton4.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
			this.bunifuButton4.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton4.OnPressedState.IconLeftImage = null;
			this.bunifuButton4.OnPressedState.IconRightImage = null;
			this.bunifuButton4.Size = new System.Drawing.Size(172, 32);
			this.bunifuButton4.TabIndex = 4;
			this.bunifuButton4.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.bunifuButton4.TextMarginLeft = 0;
			this.bunifuButton4.UseDefaultRadiusAndThickness = true;
			this.bunifuButton4.AutoSizeChanged += new System.EventHandler(this.Form1_Load);
			this.bunifuButton4.Click += new System.EventHandler(this.bunifuButton4_Click);
			// 
			// panel3
			// 
			this.panel3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(232)))), ((int)(((byte)(166)))));
			this.panel3.Location = new System.Drawing.Point(3, 74);
			this.panel3.Name = "panel3";
			this.panel3.Size = new System.Drawing.Size(6, 32);
			this.panel3.TabIndex = 3;
			// 
			// bunifuTextBox1
			// 
			this.bunifuTextBox1.AcceptsReturn = false;
			this.bunifuTextBox1.AcceptsTab = false;
			this.bunifuTextBox1.AnimationSpeed = 200;
			this.bunifuTextBox1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
			this.bunifuTextBox1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
			this.bunifuTextBox1.BackColor = System.Drawing.Color.Transparent;
			this.bunifuTextBox1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox1.BackgroundImage")));
			this.bunifuTextBox1.BorderColorActive = System.Drawing.Color.DodgerBlue;
			this.bunifuTextBox1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
			this.bunifuTextBox1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.bunifuTextBox1.BorderColorIdle = System.Drawing.Color.Silver;
			this.bunifuTextBox1.BorderRadius = 5;
			this.bunifuTextBox1.BorderThickness = 1;
			this.bunifuTextBox1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
			this.bunifuTextBox1.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox1.DefaultFont = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
			this.bunifuTextBox1.DefaultText = "";
			this.bunifuTextBox1.FillColor = System.Drawing.Color.White;
			this.bunifuTextBox1.HideSelection = true;
			this.bunifuTextBox1.IconLeft = null;
			this.bunifuTextBox1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox1.IconPadding = 10;
			this.bunifuTextBox1.IconRight = null;
			this.bunifuTextBox1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox1.Lines = new string[0];
			this.bunifuTextBox1.Location = new System.Drawing.Point(217, 116);
			this.bunifuTextBox1.MaxLength = 32767;
			this.bunifuTextBox1.MinimumSize = new System.Drawing.Size(1, 1);
			this.bunifuTextBox1.Modified = false;
			this.bunifuTextBox1.Multiline = false;
			this.bunifuTextBox1.Name = "bunifuTextBox1";
			stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
			stateProperties25.FillColor = System.Drawing.Color.Empty;
			stateProperties25.ForeColor = System.Drawing.Color.Empty;
			stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox1.OnActiveState = stateProperties25;
			stateProperties26.BorderColor = System.Drawing.Color.Empty;
			stateProperties26.FillColor = System.Drawing.Color.White;
			stateProperties26.ForeColor = System.Drawing.Color.Empty;
			stateProperties26.PlaceholderForeColor = System.Drawing.Color.Silver;
			this.bunifuTextBox1.OnDisabledState = stateProperties26;
			stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			stateProperties27.FillColor = System.Drawing.Color.Empty;
			stateProperties27.ForeColor = System.Drawing.Color.Empty;
			stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox1.OnHoverState = stateProperties27;
			stateProperties28.BorderColor = System.Drawing.Color.Silver;
			stateProperties28.FillColor = System.Drawing.Color.White;
			stateProperties28.ForeColor = System.Drawing.Color.Empty;
			stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox1.OnIdleState = stateProperties28;
			this.bunifuTextBox1.PasswordChar = '\0';
			this.bunifuTextBox1.PlaceholderForeColor = System.Drawing.Color.Silver;
			this.bunifuTextBox1.PlaceholderText = "Enter text";
			this.bunifuTextBox1.ReadOnly = false;
			this.bunifuTextBox1.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.bunifuTextBox1.SelectedText = "";
			this.bunifuTextBox1.SelectionLength = 0;
			this.bunifuTextBox1.SelectionStart = 0;
			this.bunifuTextBox1.ShortcutsEnabled = true;
			this.bunifuTextBox1.Size = new System.Drawing.Size(615, 32);
			this.bunifuTextBox1.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
			this.bunifuTextBox1.TabIndex = 3;
			this.bunifuTextBox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.bunifuTextBox1.TextMarginBottom = 0;
			this.bunifuTextBox1.TextMarginLeft = 5;
			this.bunifuTextBox1.TextMarginTop = 0;
			this.bunifuTextBox1.TextPlaceholder = "Enter text";
			this.bunifuTextBox1.UseSystemPasswordChar = false;
			this.bunifuTextBox1.WordWrap = true;
			this.bunifuTextBox1.AutoSizeChanged += new System.EventHandler(this.Form1_Load);
			// 
			// bunifuTextBox2
			// 
			this.bunifuTextBox2.AcceptsReturn = false;
			this.bunifuTextBox2.AcceptsTab = false;
			this.bunifuTextBox2.AnimationSpeed = 200;
			this.bunifuTextBox2.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
			this.bunifuTextBox2.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
			this.bunifuTextBox2.BackColor = System.Drawing.Color.Transparent;
			this.bunifuTextBox2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox2.BackgroundImage")));
			this.bunifuTextBox2.BorderColorActive = System.Drawing.Color.DodgerBlue;
			this.bunifuTextBox2.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
			this.bunifuTextBox2.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.bunifuTextBox2.BorderColorIdle = System.Drawing.Color.Silver;
			this.bunifuTextBox2.BorderRadius = 5;
			this.bunifuTextBox2.BorderThickness = 1;
			this.bunifuTextBox2.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
			this.bunifuTextBox2.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox2.DefaultFont = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
			this.bunifuTextBox2.DefaultText = "";
			this.bunifuTextBox2.FillColor = System.Drawing.Color.White;
			this.bunifuTextBox2.HideSelection = true;
			this.bunifuTextBox2.IconLeft = null;
			this.bunifuTextBox2.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox2.IconPadding = 10;
			this.bunifuTextBox2.IconRight = null;
			this.bunifuTextBox2.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox2.Lines = new string[0];
			this.bunifuTextBox2.Location = new System.Drawing.Point(215, 189);
			this.bunifuTextBox2.MaxLength = 32767;
			this.bunifuTextBox2.MinimumSize = new System.Drawing.Size(1, 1);
			this.bunifuTextBox2.Modified = false;
			this.bunifuTextBox2.Multiline = false;
			this.bunifuTextBox2.Name = "bunifuTextBox2";
			stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
			stateProperties29.FillColor = System.Drawing.Color.Empty;
			stateProperties29.ForeColor = System.Drawing.Color.Empty;
			stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox2.OnActiveState = stateProperties29;
			stateProperties30.BorderColor = System.Drawing.Color.Empty;
			stateProperties30.FillColor = System.Drawing.Color.White;
			stateProperties30.ForeColor = System.Drawing.Color.Empty;
			stateProperties30.PlaceholderForeColor = System.Drawing.Color.Silver;
			this.bunifuTextBox2.OnDisabledState = stateProperties30;
			stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			stateProperties31.FillColor = System.Drawing.Color.Empty;
			stateProperties31.ForeColor = System.Drawing.Color.Empty;
			stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox2.OnHoverState = stateProperties31;
			stateProperties32.BorderColor = System.Drawing.Color.Silver;
			stateProperties32.FillColor = System.Drawing.Color.White;
			stateProperties32.ForeColor = System.Drawing.Color.Empty;
			stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox2.OnIdleState = stateProperties32;
			this.bunifuTextBox2.PasswordChar = '\0';
			this.bunifuTextBox2.PlaceholderForeColor = System.Drawing.Color.Silver;
			this.bunifuTextBox2.PlaceholderText = "Enter text";
			this.bunifuTextBox2.ReadOnly = false;
			this.bunifuTextBox2.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.bunifuTextBox2.SelectedText = "";
			this.bunifuTextBox2.SelectionLength = 0;
			this.bunifuTextBox2.SelectionStart = 0;
			this.bunifuTextBox2.ShortcutsEnabled = true;
			this.bunifuTextBox2.Size = new System.Drawing.Size(400, 32);
			this.bunifuTextBox2.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
			this.bunifuTextBox2.TabIndex = 4;
			this.bunifuTextBox2.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.bunifuTextBox2.TextMarginBottom = 0;
			this.bunifuTextBox2.TextMarginLeft = 5;
			this.bunifuTextBox2.TextMarginTop = 0;
			this.bunifuTextBox2.TextPlaceholder = "Enter text";
			this.bunifuTextBox2.UseSystemPasswordChar = false;
			this.bunifuTextBox2.WordWrap = true;
			// 
			// label2
			// 
			this.label2.AutoSize = true;
			this.label2.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
			this.label2.ForeColor = System.Drawing.Color.White;
			this.label2.Location = new System.Drawing.Point(621, 205);
			this.label2.Name = "label2";
			this.label2.Size = new System.Drawing.Size(237, 16);
			this.label2.TabIndex = 5;
			this.label2.Text = "- хэш значение сообщения (SHA1)";
			// 
			// bunifuTextBox3
			// 
			this.bunifuTextBox3.AcceptsReturn = false;
			this.bunifuTextBox3.AcceptsTab = false;
			this.bunifuTextBox3.AnimationSpeed = 200;
			this.bunifuTextBox3.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
			this.bunifuTextBox3.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
			this.bunifuTextBox3.BackColor = System.Drawing.Color.Transparent;
			this.bunifuTextBox3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox3.BackgroundImage")));
			this.bunifuTextBox3.BorderColorActive = System.Drawing.Color.DodgerBlue;
			this.bunifuTextBox3.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
			this.bunifuTextBox3.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.bunifuTextBox3.BorderColorIdle = System.Drawing.Color.Silver;
			this.bunifuTextBox3.BorderRadius = 5;
			this.bunifuTextBox3.BorderThickness = 1;
			this.bunifuTextBox3.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
			this.bunifuTextBox3.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox3.DefaultFont = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
			this.bunifuTextBox3.DefaultText = "";
			this.bunifuTextBox3.FillColor = System.Drawing.Color.White;
			this.bunifuTextBox3.HideSelection = true;
			this.bunifuTextBox3.IconLeft = null;
			this.bunifuTextBox3.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox3.IconPadding = 10;
			this.bunifuTextBox3.IconRight = null;
			this.bunifuTextBox3.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox3.Lines = new string[0];
			this.bunifuTextBox3.Location = new System.Drawing.Point(215, 227);
			this.bunifuTextBox3.MaxLength = 32767;
			this.bunifuTextBox3.MinimumSize = new System.Drawing.Size(1, 1);
			this.bunifuTextBox3.Modified = false;
			this.bunifuTextBox3.Multiline = false;
			this.bunifuTextBox3.Name = "bunifuTextBox3";
			stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
			stateProperties33.FillColor = System.Drawing.Color.Empty;
			stateProperties33.ForeColor = System.Drawing.Color.Empty;
			stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox3.OnActiveState = stateProperties33;
			stateProperties34.BorderColor = System.Drawing.Color.Empty;
			stateProperties34.FillColor = System.Drawing.Color.White;
			stateProperties34.ForeColor = System.Drawing.Color.Empty;
			stateProperties34.PlaceholderForeColor = System.Drawing.Color.Silver;
			this.bunifuTextBox3.OnDisabledState = stateProperties34;
			stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			stateProperties35.FillColor = System.Drawing.Color.Empty;
			stateProperties35.ForeColor = System.Drawing.Color.Empty;
			stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox3.OnHoverState = stateProperties35;
			stateProperties36.BorderColor = System.Drawing.Color.Silver;
			stateProperties36.FillColor = System.Drawing.Color.White;
			stateProperties36.ForeColor = System.Drawing.Color.Empty;
			stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox3.OnIdleState = stateProperties36;
			this.bunifuTextBox3.PasswordChar = '\0';
			this.bunifuTextBox3.PlaceholderForeColor = System.Drawing.Color.Silver;
			this.bunifuTextBox3.PlaceholderText = "Enter text";
			this.bunifuTextBox3.ReadOnly = false;
			this.bunifuTextBox3.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.bunifuTextBox3.SelectedText = "";
			this.bunifuTextBox3.SelectionLength = 0;
			this.bunifuTextBox3.SelectionStart = 0;
			this.bunifuTextBox3.ShortcutsEnabled = true;
			this.bunifuTextBox3.Size = new System.Drawing.Size(180, 32);
			this.bunifuTextBox3.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
			this.bunifuTextBox3.TabIndex = 6;
			this.bunifuTextBox3.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.bunifuTextBox3.TextMarginBottom = 0;
			this.bunifuTextBox3.TextMarginLeft = 5;
			this.bunifuTextBox3.TextMarginTop = 0;
			this.bunifuTextBox3.TextPlaceholder = "Enter text";
			this.bunifuTextBox3.UseSystemPasswordChar = false;
			this.bunifuTextBox3.WordWrap = true;
			// 
			// bunifuTextBox4
			// 
			this.bunifuTextBox4.AcceptsReturn = false;
			this.bunifuTextBox4.AcceptsTab = false;
			this.bunifuTextBox4.AnimationSpeed = 200;
			this.bunifuTextBox4.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
			this.bunifuTextBox4.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
			this.bunifuTextBox4.BackColor = System.Drawing.Color.Transparent;
			this.bunifuTextBox4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox4.BackgroundImage")));
			this.bunifuTextBox4.BorderColorActive = System.Drawing.Color.DodgerBlue;
			this.bunifuTextBox4.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
			this.bunifuTextBox4.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.bunifuTextBox4.BorderColorIdle = System.Drawing.Color.Silver;
			this.bunifuTextBox4.BorderRadius = 5;
			this.bunifuTextBox4.BorderThickness = 1;
			this.bunifuTextBox4.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
			this.bunifuTextBox4.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox4.DefaultFont = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
			this.bunifuTextBox4.DefaultText = "";
			this.bunifuTextBox4.FillColor = System.Drawing.Color.White;
			this.bunifuTextBox4.HideSelection = true;
			this.bunifuTextBox4.IconLeft = null;
			this.bunifuTextBox4.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox4.IconPadding = 10;
			this.bunifuTextBox4.IconRight = null;
			this.bunifuTextBox4.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox4.Lines = new string[0];
			this.bunifuTextBox4.Location = new System.Drawing.Point(215, 265);
			this.bunifuTextBox4.MaxLength = 32767;
			this.bunifuTextBox4.MinimumSize = new System.Drawing.Size(1, 1);
			this.bunifuTextBox4.Modified = false;
			this.bunifuTextBox4.Multiline = false;
			this.bunifuTextBox4.Name = "bunifuTextBox4";
			stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
			stateProperties37.FillColor = System.Drawing.Color.Empty;
			stateProperties37.ForeColor = System.Drawing.Color.Empty;
			stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox4.OnActiveState = stateProperties37;
			stateProperties38.BorderColor = System.Drawing.Color.Empty;
			stateProperties38.FillColor = System.Drawing.Color.White;
			stateProperties38.ForeColor = System.Drawing.Color.Empty;
			stateProperties38.PlaceholderForeColor = System.Drawing.Color.Silver;
			this.bunifuTextBox4.OnDisabledState = stateProperties38;
			stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			stateProperties39.FillColor = System.Drawing.Color.Empty;
			stateProperties39.ForeColor = System.Drawing.Color.Empty;
			stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox4.OnHoverState = stateProperties39;
			stateProperties40.BorderColor = System.Drawing.Color.Silver;
			stateProperties40.FillColor = System.Drawing.Color.White;
			stateProperties40.ForeColor = System.Drawing.Color.Empty;
			stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox4.OnIdleState = stateProperties40;
			this.bunifuTextBox4.PasswordChar = '\0';
			this.bunifuTextBox4.PlaceholderForeColor = System.Drawing.Color.Silver;
			this.bunifuTextBox4.PlaceholderText = "Enter text";
			this.bunifuTextBox4.ReadOnly = false;
			this.bunifuTextBox4.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.bunifuTextBox4.SelectedText = "";
			this.bunifuTextBox4.SelectionLength = 0;
			this.bunifuTextBox4.SelectionStart = 0;
			this.bunifuTextBox4.ShortcutsEnabled = true;
			this.bunifuTextBox4.Size = new System.Drawing.Size(180, 32);
			this.bunifuTextBox4.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
			this.bunifuTextBox4.TabIndex = 7;
			this.bunifuTextBox4.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.bunifuTextBox4.TextMarginBottom = 0;
			this.bunifuTextBox4.TextMarginLeft = 5;
			this.bunifuTextBox4.TextMarginTop = 0;
			this.bunifuTextBox4.TextPlaceholder = "Enter text";
			this.bunifuTextBox4.UseSystemPasswordChar = false;
			this.bunifuTextBox4.WordWrap = true;
			// 
			// bunifuTextBox5
			// 
			this.bunifuTextBox5.AcceptsReturn = false;
			this.bunifuTextBox5.AcceptsTab = false;
			this.bunifuTextBox5.AnimationSpeed = 200;
			this.bunifuTextBox5.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
			this.bunifuTextBox5.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
			this.bunifuTextBox5.BackColor = System.Drawing.Color.Transparent;
			this.bunifuTextBox5.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox5.BackgroundImage")));
			this.bunifuTextBox5.BorderColorActive = System.Drawing.Color.DodgerBlue;
			this.bunifuTextBox5.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
			this.bunifuTextBox5.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.bunifuTextBox5.BorderColorIdle = System.Drawing.Color.Silver;
			this.bunifuTextBox5.BorderRadius = 5;
			this.bunifuTextBox5.BorderThickness = 1;
			this.bunifuTextBox5.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
			this.bunifuTextBox5.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox5.DefaultFont = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
			this.bunifuTextBox5.DefaultText = "";
			this.bunifuTextBox5.FillColor = System.Drawing.Color.White;
			this.bunifuTextBox5.HideSelection = true;
			this.bunifuTextBox5.IconLeft = null;
			this.bunifuTextBox5.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox5.IconPadding = 10;
			this.bunifuTextBox5.IconRight = null;
			this.bunifuTextBox5.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox5.Lines = new string[0];
			this.bunifuTextBox5.Location = new System.Drawing.Point(215, 303);
			this.bunifuTextBox5.MaxLength = 32767;
			this.bunifuTextBox5.MinimumSize = new System.Drawing.Size(1, 1);
			this.bunifuTextBox5.Modified = false;
			this.bunifuTextBox5.Multiline = false;
			this.bunifuTextBox5.Name = "bunifuTextBox5";
			stateProperties41.BorderColor = System.Drawing.Color.DodgerBlue;
			stateProperties41.FillColor = System.Drawing.Color.Empty;
			stateProperties41.ForeColor = System.Drawing.Color.Empty;
			stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox5.OnActiveState = stateProperties41;
			stateProperties42.BorderColor = System.Drawing.Color.Empty;
			stateProperties42.FillColor = System.Drawing.Color.White;
			stateProperties42.ForeColor = System.Drawing.Color.Empty;
			stateProperties42.PlaceholderForeColor = System.Drawing.Color.Silver;
			this.bunifuTextBox5.OnDisabledState = stateProperties42;
			stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			stateProperties43.FillColor = System.Drawing.Color.Empty;
			stateProperties43.ForeColor = System.Drawing.Color.Empty;
			stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox5.OnHoverState = stateProperties43;
			stateProperties44.BorderColor = System.Drawing.Color.Silver;
			stateProperties44.FillColor = System.Drawing.Color.White;
			stateProperties44.ForeColor = System.Drawing.Color.Empty;
			stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox5.OnIdleState = stateProperties44;
			this.bunifuTextBox5.PasswordChar = '\0';
			this.bunifuTextBox5.PlaceholderForeColor = System.Drawing.Color.Silver;
			this.bunifuTextBox5.PlaceholderText = "Enter text";
			this.bunifuTextBox5.ReadOnly = false;
			this.bunifuTextBox5.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.bunifuTextBox5.SelectedText = "";
			this.bunifuTextBox5.SelectionLength = 0;
			this.bunifuTextBox5.SelectionStart = 0;
			this.bunifuTextBox5.ShortcutsEnabled = true;
			this.bunifuTextBox5.Size = new System.Drawing.Size(180, 32);
			this.bunifuTextBox5.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
			this.bunifuTextBox5.TabIndex = 8;
			this.bunifuTextBox5.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.bunifuTextBox5.TextMarginBottom = 0;
			this.bunifuTextBox5.TextMarginLeft = 5;
			this.bunifuTextBox5.TextMarginTop = 0;
			this.bunifuTextBox5.TextPlaceholder = "Enter text";
			this.bunifuTextBox5.UseSystemPasswordChar = false;
			this.bunifuTextBox5.WordWrap = true;
			// 
			// bunifuTextBox6
			// 
			this.bunifuTextBox6.AcceptsReturn = false;
			this.bunifuTextBox6.AcceptsTab = false;
			this.bunifuTextBox6.AnimationSpeed = 200;
			this.bunifuTextBox6.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
			this.bunifuTextBox6.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
			this.bunifuTextBox6.BackColor = System.Drawing.Color.Transparent;
			this.bunifuTextBox6.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox6.BackgroundImage")));
			this.bunifuTextBox6.BorderColorActive = System.Drawing.Color.DodgerBlue;
			this.bunifuTextBox6.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
			this.bunifuTextBox6.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.bunifuTextBox6.BorderColorIdle = System.Drawing.Color.Silver;
			this.bunifuTextBox6.BorderRadius = 5;
			this.bunifuTextBox6.BorderThickness = 1;
			this.bunifuTextBox6.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
			this.bunifuTextBox6.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox6.DefaultFont = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
			this.bunifuTextBox6.DefaultText = "";
			this.bunifuTextBox6.FillColor = System.Drawing.Color.White;
			this.bunifuTextBox6.HideSelection = true;
			this.bunifuTextBox6.IconLeft = null;
			this.bunifuTextBox6.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox6.IconPadding = 10;
			this.bunifuTextBox6.IconRight = null;
			this.bunifuTextBox6.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox6.Lines = new string[0];
			this.bunifuTextBox6.Location = new System.Drawing.Point(215, 341);
			this.bunifuTextBox6.MaxLength = 32767;
			this.bunifuTextBox6.MinimumSize = new System.Drawing.Size(1, 1);
			this.bunifuTextBox6.Modified = false;
			this.bunifuTextBox6.Multiline = false;
			this.bunifuTextBox6.Name = "bunifuTextBox6";
			stateProperties45.BorderColor = System.Drawing.Color.DodgerBlue;
			stateProperties45.FillColor = System.Drawing.Color.Empty;
			stateProperties45.ForeColor = System.Drawing.Color.Empty;
			stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox6.OnActiveState = stateProperties45;
			stateProperties46.BorderColor = System.Drawing.Color.Empty;
			stateProperties46.FillColor = System.Drawing.Color.White;
			stateProperties46.ForeColor = System.Drawing.Color.Empty;
			stateProperties46.PlaceholderForeColor = System.Drawing.Color.Silver;
			this.bunifuTextBox6.OnDisabledState = stateProperties46;
			stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			stateProperties47.FillColor = System.Drawing.Color.Empty;
			stateProperties47.ForeColor = System.Drawing.Color.Empty;
			stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox6.OnHoverState = stateProperties47;
			stateProperties48.BorderColor = System.Drawing.Color.Silver;
			stateProperties48.FillColor = System.Drawing.Color.White;
			stateProperties48.ForeColor = System.Drawing.Color.Empty;
			stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox6.OnIdleState = stateProperties48;
			this.bunifuTextBox6.PasswordChar = '\0';
			this.bunifuTextBox6.PlaceholderForeColor = System.Drawing.Color.Silver;
			this.bunifuTextBox6.PlaceholderText = "Enter text";
			this.bunifuTextBox6.ReadOnly = false;
			this.bunifuTextBox6.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.bunifuTextBox6.SelectedText = "";
			this.bunifuTextBox6.SelectionLength = 0;
			this.bunifuTextBox6.SelectionStart = 0;
			this.bunifuTextBox6.ShortcutsEnabled = true;
			this.bunifuTextBox6.Size = new System.Drawing.Size(180, 32);
			this.bunifuTextBox6.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
			this.bunifuTextBox6.TabIndex = 9;
			this.bunifuTextBox6.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.bunifuTextBox6.TextMarginBottom = 0;
			this.bunifuTextBox6.TextMarginLeft = 5;
			this.bunifuTextBox6.TextMarginTop = 0;
			this.bunifuTextBox6.TextPlaceholder = "Enter text";
			this.bunifuTextBox6.UseSystemPasswordChar = false;
			this.bunifuTextBox6.WordWrap = true;
			// 
			// label3
			// 
			this.label3.AutoSize = true;
			this.label3.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
			this.label3.ForeColor = System.Drawing.Color.White;
			this.label3.Location = new System.Drawing.Point(401, 357);
			this.label3.Name = "label3";
			this.label3.Size = new System.Drawing.Size(134, 16);
			this.label3.TabIndex = 10;
			this.label3.Text = "- x, закрытый ключ";
			// 
			// label4
			// 
			this.label4.AutoSize = true;
			this.label4.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
			this.label4.ForeColor = System.Drawing.Color.White;
			this.label4.Location = new System.Drawing.Point(401, 319);
			this.label4.Name = "label4";
			this.label4.Size = new System.Drawing.Size(135, 16);
			this.label4.TabIndex = 11;
			this.label4.Text = "- у, открытый ключ";
			// 
			// label5
			// 
			this.label5.AutoSize = true;
			this.label5.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
			this.label5.ForeColor = System.Drawing.Color.White;
			this.label5.Location = new System.Drawing.Point(401, 243);
			this.label5.Name = "label5";
			this.label5.Size = new System.Drawing.Size(132, 16);
			this.label5.TabIndex = 12;
			this.label5.Text = "- q, простое число";
			// 
			// label6
			// 
			this.label6.AutoSize = true;
			this.label6.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
			this.label6.ForeColor = System.Drawing.Color.White;
			this.label6.Location = new System.Drawing.Point(401, 281);
			this.label6.Name = "label6";
			this.label6.Size = new System.Drawing.Size(132, 16);
			this.label6.TabIndex = 13;
			this.label6.Text = "- p, простое число";
			// 
			// bunifuButton6
			// 
			this.bunifuButton6.AllowToggling = false;
			this.bunifuButton6.AnimationSpeed = 200;
			this.bunifuButton6.AutoGenerateColors = false;
			this.bunifuButton6.BackColor = System.Drawing.Color.Transparent;
			this.bunifuButton6.BackColor1 = System.Drawing.Color.Transparent;
			this.bunifuButton6.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton6.BackgroundImage")));
			this.bunifuButton6.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
			this.bunifuButton6.ButtonText = "Сгенерировать парамметры";
			this.bunifuButton6.ButtonTextMarginLeft = 0;
			this.bunifuButton6.ColorContrastOnClick = 45;
			this.bunifuButton6.ColorContrastOnHover = 45;
			this.bunifuButton6.Cursor = System.Windows.Forms.Cursors.Hand;
			borderEdges12.BottomLeft = true;
			borderEdges12.BottomRight = true;
			borderEdges12.TopLeft = true;
			borderEdges12.TopRight = true;
			this.bunifuButton6.CustomizableEdges = borderEdges12;
			this.bunifuButton6.DialogResult = System.Windows.Forms.DialogResult.None;
			this.bunifuButton6.DisabledBorderColor = System.Drawing.Color.Empty;
			this.bunifuButton6.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuButton6.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.bunifuButton6.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			this.bunifuButton6.Font = new System.Drawing.Font("Century Gothic", 12F);
			this.bunifuButton6.ForeColor = System.Drawing.Color.White;
			this.bunifuButton6.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
			this.bunifuButton6.IconMarginLeft = 7;
			this.bunifuButton6.IconPadding = 4;
			this.bunifuButton6.IconRightCursor = System.Windows.Forms.Cursors.Hand;
			this.bunifuButton6.IdleBorderColor = System.Drawing.Color.White;
			this.bunifuButton6.IdleBorderRadius = 3;
			this.bunifuButton6.IdleBorderThickness = 1;
			this.bunifuButton6.IdleFillColor = System.Drawing.Color.Transparent;
			this.bunifuButton6.IdleIconLeftImage = null;
			this.bunifuButton6.IdleIconRightImage = null;
			this.bunifuButton6.IndicateFocus = false;
			this.bunifuButton6.Location = new System.Drawing.Point(215, 421);
			this.bunifuButton6.Name = "bunifuButton6";
			this.bunifuButton6.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.bunifuButton6.onHoverState.BorderRadius = 3;
			this.bunifuButton6.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton6.onHoverState.BorderThickness = 1;
			this.bunifuButton6.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.bunifuButton6.onHoverState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton6.onHoverState.IconLeftImage = null;
			this.bunifuButton6.onHoverState.IconRightImage = null;
			this.bunifuButton6.OnIdleState.BorderColor = System.Drawing.Color.White;
			this.bunifuButton6.OnIdleState.BorderRadius = 3;
			this.bunifuButton6.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dot;
			this.bunifuButton6.OnIdleState.BorderThickness = 1;
			this.bunifuButton6.OnIdleState.FillColor = System.Drawing.Color.Transparent;
			this.bunifuButton6.OnIdleState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton6.OnIdleState.IconLeftImage = null;
			this.bunifuButton6.OnIdleState.IconRightImage = null;
			this.bunifuButton6.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
			this.bunifuButton6.OnPressedState.BorderRadius = 3;
			this.bunifuButton6.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton6.OnPressedState.BorderThickness = 1;
			this.bunifuButton6.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
			this.bunifuButton6.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton6.OnPressedState.IconLeftImage = null;
			this.bunifuButton6.OnPressedState.IconRightImage = null;
			this.bunifuButton6.Size = new System.Drawing.Size(248, 32);
			this.bunifuButton6.TabIndex = 6;
			this.bunifuButton6.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.bunifuButton6.TextMarginLeft = 0;
			this.bunifuButton6.UseDefaultRadiusAndThickness = true;
			this.bunifuButton6.Click += new System.EventHandler(this.bunifuButton6_Click);
			// 
			// bunifuFormDock1
			// 
			this.bunifuFormDock1.AllowFormDragging = true;
			this.bunifuFormDock1.AllowFormDropShadow = true;
			this.bunifuFormDock1.AllowFormResizing = true;
			this.bunifuFormDock1.AllowHidingBottomRegion = true;
			this.bunifuFormDock1.AllowOpacityChangesWhileDragging = false;
			this.bunifuFormDock1.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
			this.bunifuFormDock1.BorderOptions.BottomBorder.BorderThickness = 1;
			this.bunifuFormDock1.BorderOptions.BottomBorder.ShowBorder = true;
			this.bunifuFormDock1.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
			this.bunifuFormDock1.BorderOptions.LeftBorder.BorderThickness = 1;
			this.bunifuFormDock1.BorderOptions.LeftBorder.ShowBorder = true;
			this.bunifuFormDock1.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
			this.bunifuFormDock1.BorderOptions.RightBorder.BorderThickness = 1;
			this.bunifuFormDock1.BorderOptions.RightBorder.ShowBorder = true;
			this.bunifuFormDock1.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
			this.bunifuFormDock1.BorderOptions.TopBorder.BorderThickness = 1;
			this.bunifuFormDock1.BorderOptions.TopBorder.ShowBorder = true;
			this.bunifuFormDock1.ContainerControl = this;
			this.bunifuFormDock1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
			this.bunifuFormDock1.DockingIndicatorsOpacity = 0.7D;
			this.bunifuFormDock1.DockingOptions.DockAll = true;
			this.bunifuFormDock1.DockingOptions.DockBottomLeft = true;
			this.bunifuFormDock1.DockingOptions.DockBottomRight = true;
			this.bunifuFormDock1.DockingOptions.DockFullScreen = true;
			this.bunifuFormDock1.DockingOptions.DockLeft = true;
			this.bunifuFormDock1.DockingOptions.DockRight = true;
			this.bunifuFormDock1.DockingOptions.DockTopLeft = true;
			this.bunifuFormDock1.DockingOptions.DockTopRight = true;
			this.bunifuFormDock1.FormDraggingOpacity = 0.8D;
			this.bunifuFormDock1.ParentForm = this;
			this.bunifuFormDock1.ShowCursorChanges = true;
			this.bunifuFormDock1.ShowDockingIndicators = true;
			this.bunifuFormDock1.TitleBarOptions.AllowFormDragging = true;
			this.bunifuFormDock1.TitleBarOptions.BunifuFormDock = this.bunifuFormDock1;
			this.bunifuFormDock1.TitleBarOptions.DoubleClickToExpandWindow = true;
			this.bunifuFormDock1.TitleBarOptions.TitleBarControl = null;
			this.bunifuFormDock1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
			// 
			// Form1
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
			this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(43)))), ((int)(((byte)(60)))));
			this.ClientSize = new System.Drawing.Size(872, 510);
			this.Controls.Add(this.bunifuButton6);
			this.Controls.Add(this.label6);
			this.Controls.Add(this.label5);
			this.Controls.Add(this.label4);
			this.Controls.Add(this.label3);
			this.Controls.Add(this.bunifuTextBox6);
			this.Controls.Add(this.bunifuTextBox5);
			this.Controls.Add(this.bunifuTextBox4);
			this.Controls.Add(this.bunifuTextBox3);
			this.Controls.Add(this.label2);
			this.Controls.Add(this.bunifuTextBox2);
			this.Controls.Add(this.bunifuTextBox1);
			this.Controls.Add(this.panel2);
			this.Controls.Add(this.panel1);
			this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
			this.Name = "Form1";
			this.Text = "Form1";
			this.Load += new System.EventHandler(this.Form1_Load);
			this.panel1.ResumeLayout(false);
			this.panel1.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
			this.panel2.ResumeLayout(false);
			this.ResumeLayout(false);
			this.PerformLayout();

		}

		#endregion

		private System.Windows.Forms.Panel panel1;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton3;
		private System.Windows.Forms.Panel panel2;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton5;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton4;
		private System.Windows.Forms.Panel panel3;
		private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
		private System.Windows.Forms.Label label1;
		private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox bunifuTextBox1;
		private System.Windows.Forms.Label label2;
		private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox bunifuTextBox2;
		private System.Windows.Forms.Label label6;
		private System.Windows.Forms.Label label5;
		private System.Windows.Forms.Label label4;
		private System.Windows.Forms.Label label3;
		private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox bunifuTextBox6;
		private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox bunifuTextBox5;
		private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox bunifuTextBox4;
		private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox bunifuTextBox3;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton6;
		private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock1;
	}
}

